import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Archivo_Narrow, Bricolage_Grotesque, Geist } from "next/font/google";
import { twMerge } from "tailwind-merge";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const p = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-p",
  weight: ["400", "500", "600", "700"],
});

const header = Archivo_Narrow({
  subsets: ["latin"],
  variable: "--font-header",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={twMerge("h-full", "antialiased", p.variable, header.variable, "font-sans", geist.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          storageKey={undefined}
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          {process.env.NODE_ENV === "development" && (
            <script
              src="https://unpkg.com/react-scan/dist/auto.global.js"
              crossOrigin="anonymous"
            />
          )}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
